### ISSUE TITLE
Researcher/user can easily browse old research

### ISSUE THREAD

**Issue by simone-smith** [guardian/panopticon#1]
As a researcher/user
I want to easily browse old research
So that I don't need to ask other people for it.

**Acceptance criteria**
- [ ] A user can see a table listing all stored research projects by orderable columns (title, year, quarter, team, OKR, objective, research owner, product owner, tags)
- [ ] A user can click to easily sort each column alphabetically or by date
- [ ] A user can click on a record row and see more detailed information, including objective and thumbnails/links to outputs
- [ ] A user can click on the thumbnails/links to outputs and preview the file via Google Drive, and hit a close button to return to the overview table
- [ ] A user can see a filter/search bar above the table and use it to search for and select tags to filter research records. 
- [ ] A user can see a welcome page featuring suggested tags and a carousel of recent research above the table
